In [1]:
import pandas as pd
import numpy as np

In [ ]:
df_train = pd.read_csv("../data/train.csv")
df_train.head()

,ID,Age,Gender,Country,Race,Family_Background,Radiation_History,Iodine_Deficiency,Smoke,Weight_Risk,Diabetes,Nodule_Size,TSH_Result,T4_Result,T3_Result,Cancer
0,TRAIN_00000,80,M,CHN,ASN,Positive,Exposed,Sufficient,Non-Smoker,Not Obese,No,0.650355,2.784735,6.744603,2.575820,1
1,TRAIN_00001,37,M,NGA,ASN,Positive,Unexposed,Sufficient,Smoker,Obese,No,2.950430,0.911624,7.303305,2.505317,1
2,TRAIN_00002,71,M,CHN,MDE,Positive,Unexposed,Sufficient,Non-Smoker,Not Obese,Yes,2.200023,0.717754,11.137459,2.381080,0
3,TRAIN_00003,40,F,IND,HSP,Negative,Unexposed,Sufficient,Non-Smoker,Obese,No,3.370796,6.846380,10.175254,0.753023,0
4,TRAIN_00004,53,F,CHN,CAU,Negative,Unexposed,Sufficient,Non-Smoker,Not Obese,No,4.230048,0.439519,7.194450,0.569356,1

In [7]:
df_test = pd.read_csv("../data/test.csv")
df_test.head()

,ID,Age,Gender,Country,Race,Family_Background,Radiation_History,Iodine_Deficiency,Smoke,Weight_Risk,Diabetes,Nodule_Size,TSH_Result,T4_Result,T3_Result
0,TEST_00000,53,M,NGA,CAU,Negative,Unexposed,Sufficient,Non-Smoker,Not Obese,No,2.940678,6.434501,9.227958,2.733846
1,TEST_00001,46,M,KOR,MDE,Negative,Unexposed,Deficient,Smoker,Obese,No,3.450129,4.729535,5.937664,0.775012
2,TEST_00002,78,F,IND,ASN,Negative,Exposed,Sufficient,Non-Smoker,Obese,No,4.680720,5.663475,10.455964,1.259896
3,TEST_00003,69,F,KOR,CAU,Negative,Unexposed,Sufficient,Non-Smoker,Not Obese,No,4.280588,7.473752,8.785335,2.826138
4,TEST_00004,77,F,KOR,CAU,Positive,Unexposed,Sufficient,Non-Smoker,Obese,No,3.380094,7.099987,8.737063,3.453563

In [8]:
df_train.shape

(87159, 16)

In [ ]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87159 entries, 0 to 87158
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID                 87159 non-null  object
 1   Age                87159 non-null  int64
 2   Gender             87159 non-null  object
 3   Country            87159 non-null  object
 4   Race               87159 non-null  object
 5   Family_Background  87159 non-null  object
 6   Radiation_History  87159 non-null  object
 7   Iodine_Deficiency  87159 non-null  object
 8   Smoke              87159 non-null  object
 9   Weight_Risk        87159 non-null  object
 10  Diabetes           87159 non-null  object
 11  Nodule_Size        87159 non-null  float64
 12  TSH_Result         87159 non-null  float64
 13  T4_Result          87159 non-null  float64
 14  T3_Result          87159 non-null  float64
 15  Cancer             87159 non-null  int64
dtypes: float64(4), int64(2), object(10)
memory usage: 10.6+ MB

Dataset Info.


train.csv [파일]

ID : 샘플별 고유 ID

Age : 환자의 나이

Gender : 성별

Country : 국적

Race : 인종

Family_Background : 가족력 여부

Radiation_History : 방사선 노출 이력

Iodine_Deficiency : 요오드 결핍 여부

Smoke : 흡연 여부

Weight_Risk : 체중 관련 위험도

Diabetes : 당뇨병 여부

Nodule_Size : 갑상선 결절 크기

TSH_Result : TSH 호르몬 검사 결과

T4_Result : T4 호르몬 검사 결과

T3_Result : T3 호르몬 검사 결과

Cancer : 갑상선암 여부 (0: 양성, 1: 악성)


test.csv [파일]

ID : 샘플별 고유 ID

Cancer를 제외한 train.csv와 동일한 형태


sample_submission.csv [파일] - 제출 양식

ID : 샘플별 고유 ID

Cancer : 갑상선암 여부 (0: 양성, 1: 악성)

In [10]:
df_train.describe()

,Age,Nodule_Size,TSH_Result,T4_Result,T3_Result,Cancer
count,87159.000000,87159.000000,87159.000000,87159.000000,87159.000000,87159.000000
mean,50.860244,2.508098,5.056871,8.248796,2.005002,0.119999
std,21.638687,1.441928,2.861229,2.165975,0.867013,0.324962
min,14.000000,0.000000,0.100000,4.500000,0.500000,0.000000
25%,32.000000,1.270332,2.582845,6.372031,1.254836,0.000000
50%,51.000000,2.520941,5.059085,8.236789,2.004101,0.000000
75%,70.000000,3.760938,7.541586,10.126981,2.758032,0.000000
max,88.000000,5.000000,10.000000,12.000000,3.500000,1.000000